name: reviewdog
on: [pull_request]

jobs:
  markdownlint:
    name: runner / markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: markdownlint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          node_modules/.bin/markdownlint-cli2 "**/*.md" "#node_modules" | reviewdog -reporter=github-pr-review -filter-mode=file -efm='%f:%l:%c:%m'
